### ISSUE TITLE
Adds an extra style tag to root xml tag.

### ISSUE THREAD

**Issue by sindrit** [Jared314/chrome-xml-viewer#1]
The xml document I'm reading contains the following:

```
<?xml version="1.0" encoding="UTF-8"?> 

<iptc/> 
```

The XML viewer adds an extra '&lt;style&gt;' tag in it's version and shows me:

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<iptc>
  <style/>
</iptc>
```

I'm using Chrome 7.0.517.41 beta on Ubuntu 10.04.

**Comment by Jared314** [comment]
Have you tried it with all other extensions disabled (Adblock, etc)? Could be another chrome extension inserting dom nodes.

**Comment by sindrit** [comment]
Yeah, just tried disabling AdBlock and the style tag went away. I'll try filing a bug there.
