### ISSUE TITLE
Link to chrome store broken

### ISSUE THREAD

**Issue by Davorak** [Jared314/chrome-xml-viewer#4]
The link to the chrome store is broken:
![image](https://cloud.githubusercontent.com/assets/810921/4451159/30368100-4830-11e4-9308-816582264724.png)

![image](https://cloud.githubusercontent.com/assets/810921/4451163/4eba566a-4830-11e4-961e-08eab9569efb.png)

**Comment by Jared314** [comment]
Ah yes, the link is broken because I removed the extension from the store several years ago. There are far better xml viewer extensions available now.

The link has been removed from the repository description.
